### ISSUE TITLE
Components Issue

### ISSUE THREAD

**Issue by RafalBuchner** [mekkablue/ShowFilledPreview#4]
When ShowFilledPreview is turned on, GlyphsApp has a problem with displaying components in non acitve glyphs.
For example: here, I wrote "nnnn":
![zrzut ekranu 2016-08-05 o 20 39 55](https://cloud.githubusercontent.com/assets/18727963/17447077/cacfc664-5b4c-11e6-8e71-ab42df103404.png)

**Comment by mekkablue** [comment]
Latest upload should fix it. Thx for reporting.
