### ISSUE TITLE
Customise color

### ISSUE THREAD

**Issue by NicholasSloan** [mekkablue/ShowFilledPreview#5]
Hi Rainer, in previous version of this plugin it used to be possible to customise the grey preview colour by tweaking the line specifying the colour (…NSColor.GrayColor…?), but that bit of code seems to have disappeared. How would I make the filled preview paler now?
Thanks, Nick Sloan

**Comment by NicholasSloan** [comment]
Also Rainer, I'd say there was a case for making the default fill colour paler anyway. My experience is that you only need enough colour to give a sense of mass in the filled area. A very pale tint achieves that. Anything darker starts to compromise a clear view of the edges, and control points. Your judgement of course.

**Comment by mekkablue** [comment]
I could add an opacity setting. Would that help?

**Comment by NicholasSloan** [comment]
If that affected the fill only I think it would be a good solution Rainer. Thanks. Would this be controlled via a setting in the py file?

**Comment by mekkablue** [comment]
Update to the latest version, type and run this in Macro Window:

```python
Glyphs.defaults["com.mekkablue.ShowFilledPreview.opacity"]=0.7
```

…for setting the opacity to 70%.
